replicaCount: 3

image:
  repository: adminer
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

postgres:
  host: postgres-sts

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 50